const contractAddress = "0xD0D989ebF51eA102CBf7813B03a90f15dEbe727C"; // Replace with your own contract address 
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Witamy na stronie DES 2022 generacji tokenów niewymienialnych [NFT]!!";
const welcome_h2 = "Podłącz portfel MetaMask aby rozpocząć ;-)";
const welcome_p = 'Projekt ten ma na celu pokazanie funkcjonalności zdecentralizowanych tokenów niewymienialnych [NFT] jako certyfikatów uczestnictwa w konferencji DES 2022.';
const h1_presale_coming_soon = "AirDrop Wkrótce!!";
const h1_presale_mint = "Przedsprzedaz Otwarta!!";
const h1_public_mint = "Publiczna Sprzedaz Otwarta!!";
const h2_presale_coming_soon = "Odliczanie do przedsprzedazy";
const h2_presale_mint = "Odliczanie do upublicznienia certyfikatów";
const p_presale_coming_soon = "Pracujemy cięzko nad naszą kolekcją NFT. Wróć do nas niebawem!";
const p_presale_mint_not_whitelisted = "Nie ma Ciebie na liście do przedsprzedazy.. 😢";
const p_presale_mint_whitelisted = "Jesteś na liście do przedsprzedazy! 🎉";
const p_presale_mint_already_minted = "Odebrałeś juz swój certyfikat! 🎉";
const p_public_mint = "Publiczna sprzedaz jest juz dostępna! 🎉";
const button_presale_coming_soon = "Dołącz do listy zainteresowanych";
const button_presale_mint_whitelisted = "Wygenruj swój specjalny NFT";
const button_presale_mint_not_whitelisted = "Dołącz do listy zainteresownaych";
const button_presale_already_minted = "Dołącz do naszej społeczności";
const button_public_mint = "Wygeneruj swój NFT";
const mint_failed = "Coś poszło nie tak. 😢 Spróbuj ponownie.";
